# Generated by Django 2.1 on 2018-08-13 18:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 8, 13, 18, 29, 36, 756853, tzinfo=utc), verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2018, 8, 13, 18, 29, 36, 756853, tzinfo=utc), verbose_name='updated at')),
            ],
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 18, 29, 36, 701867, tzinfo=utc), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 18, 29, 36, 702866, tzinfo=utc), verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='team',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization'),
        ),
    ]
