# Generated by Django 2.1 on 2018-08-13 18:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20180814_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 18, 36, 42, 726238, tzinfo=utc), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 18, 36, 42, 726238, tzinfo=utc), verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 18, 36, 42, 770231, tzinfo=utc), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 18, 36, 42, 770231, tzinfo=utc), verbose_name='updated at'),
        ),
    ]
